kind: CronJob
apiVersion: batch/v1
metadata:
  name: jellyplex-watched
  namespace: jellyplex-watched
spec:
  schedule: "0 4 * * *"
  timeZone: "America/Detroit"
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: jellyplex-watched
        spec:
          restartPolicy: OnFailure
          containers:
            - name: jellyplex-watched
              image: jellyplex-watched
              imagePullPolicy: IfNotPresent
              env:
                - name: PUID
                  value: "1000"
                - name: PGID
                  value: "1000"
                - name: TZ
                  value: "America/Detroit"
                - name: JELLYFIN_TOKEN
                  valueFrom:
                    secretKeyRef:
                      name: secret-config
                      key: JELLYFIN_TOKEN
                - name: PLEX_TOKEN
                  valueFrom:
                    secretKeyRef:
                      name: secret-config
                      key: PLEX_TOKEN
                - name: USER_MAPPING
                  valueFrom:
                    secretKeyRef:
                      name: secret-config
                      key: USER_MAPPING
              envFrom:
              - configMapRef:
                  name: plain-config
              resources: {}
