---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: secret-config
  namespace: jellyplex-watched
spec:
  target:
    name: secret-config
    deletionPolicy: Delete
    template:
      type: Opaque
      data:
        JELLYFIN_TOKEN: "{{ .jellyfinToken }}"
        PLEX_TOKEN: "{{ .plexToken }}"
        USER_MAPPING: "{{ .userMapping }}"
  data:
    - secretKey: jellyfinToken
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: c8d4c28c-d80a-4862-9879-366d97b64df9
        metadataPolicy: None
        property: password
      sourceRef:
        storeRef:
          name: bitwarden-login
          kind: ClusterSecretStore
    - secretKey: plexToken
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: 371cf622-264e-4e4e-b0f4-b75691420fdb
        metadataPolicy: None
        property: password
      sourceRef:
        storeRef:
          name: bitwarden-login
          kind: ClusterSecretStore
    - secretKey: userMapping
      sourceRef:
        storeRef:
          name: bitwarden-notes
          kind: ClusterSecretStore
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: jellyplex-user-mapping
        metadataPolicy: None
