---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: secret-config
  namespace: jellyplex-watched
spec:
  target:
    name: secret-config
    deletionPolicy: Delete
    template:
      type: Opaque
      data:
        {{ .config }}
  data:
    - secretKey: config
      sourceRef:
        storeRef:
          name: bitwarden-notes
          kind: ClusterSecretStore
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: jellyplex-config
        metadataPolicy: None
